### ISSUE TITLE
No output message on click or check

### ISSUE THREAD

**Issue by sotima** [node-red-hitachi/ui_list#3]
Hi, this ui-list seems to be perfect for my project. But cannot get an output-message when I do click or check an item, although I have the action set to click or check. I am using Node-Red V 0.19.4 with dashboard V 2.10.0. (Using your example flow)

**Comment by HiroyasuNishiyama** [comment]
Hi, thank you for trying `ui_list` node.
Unfortunately, I can not guess the cause of your problem.
Could you check if there are any errors reported in developer console of your browser?

**Comment by sotima** [comment]
Hi, thank you for your fast response! I just updated to 0.1.3 and the error is gone! Works as described! Thank you very much for your efforts!
